### ISSUE TITLE
Image Indexing Issue with Non-JPG images

### ISSUE THREAD

**Issue by punyidea** [m4-k131/dream-cli#1]
Howdy!

I've used the script for the last few days and I've really gotten to enjoy it! I have found this issue, however. If an image in the directory exists and it is not of a JPG extension, it interferes with the indexing displayed on screen.

So for instance, in the image selection menu, if I have the following images im my directory:

a.jpg
b.JPEG
c.jpg
d.jpg

I see the following:
Select Image:
0:a.jpg
2:c.jpg
3:d.jpg

However, selecting 2 actually selects d.jpg and selecting 3 results in an error.

**Comment by m4-k131** [comment]
Thanks for your report, the cli only displays files that end with ".jpg". I don't know why b.JPEG gets filtered out incorrectly, i am looking into it.

**Comment by m4-k131** [comment]
I updated the function, please let me know if it solved your problem.

**Comment by punyidea** [comment]
Yes, that fixed it!
